### ISSUE TITLE
Vulpkanin tails ignore body colour, custom tails are funky too

### ISSUE THREAD

**Issue by SingoDingo** [Eclipse-Station/NEV-Northern-Light#24] opened 2020-05-05 09:19 UTC
I can't find anything to change the colour of the default vulp tail, and it's usually tied to body colour.
<img width="107" alt="XBgODEkBle" src="https://user-images.githubusercontent.com/26727780/81051374-edc56800-8f04-11ea-92e8-af99348aa94c.png">

Most custom tails seem to be colourable (made white in the below image for constrast), and would be an adequate replacement, but are automatically placed behind the player sprite. Leading to strange connections from the back view.

<img width="99" alt="Gesdh8AaWo" src="https://user-images.githubusercontent.com/26727780/81051557-39781180-8f05-11ea-9ec8-628fe61b7842.png">

**Comment by EvilJackCarver** [comment] 2020-05-07 00:37
Duplicate of #21, duplicated by #26. 

I'm closing this one as duplicate in favour of #26; even though this is an older issue #26's scope is a bit more accurate.

**Closed by EvilJackCarver** 2020-05-07 00:37 UTC
Labels: Sprites, bug, duplicate
