### ISSUE TITLE
Biogenerator doesn't seem to work.

### ISSUE THREAD

**Issue by Leon9621** [Eclipse-Station/NEV-Northern-Light#293] opened 2020-07-07 10:13 UTC
To be clear, this is in regards to the power producing machine itself. I had a large canister of biomass with about 170 units loaded, the oxygen was flowing, the waste gas was ready to be pumped into the cans, and the machine itself said we were all clear. Despite all of this, activating the biogenerator would work for possible a split second before immediately shutting itself off, without producing any power. The sprite on the leftmost machine would activate and immediately empty. Oxygen flow started at base 101.35 or so, and I cranked up up to 15k later, still nothing.

**Comment by EvilJackCarver** [comment] 2020-07-08 23:10
Can somebody confirm whether this is an issue with the biogenerator or user error?

**Comment by EvilJackCarver** [comment] 2020-07-11 01:52
Reproduced: It IS an issue with the biogenerator. It IS NOT operator error.

The ui_interact() proc is not properly passing on the activate() and deactivate() procs to the biogenerator datum. Manually setting the `working` var or calling activate() and deactivate() does start and stop it.

**Comment by ShadzFen** [comment] 2020-07-13 16:33
Duplicate of https://github.com/Eclipse-Station/NEV-Northern-Light/issues/247 but with more info. Latest update allegedly fixed this issue.
![image](https://user-images.githubusercontent.com/45645502/87329477-49c8f000-c537-11ea-950d-05230c1e013f.png)

**Closed** 2020-07-14 14:28 UTC
Labels: bug
