### ISSUE TITLE
Soulcrypts are not recognized by body scanners

### ISSUE THREAD

**Issue by cruxxansata** [Eclipse-Station/NEV-Northern-Light#372] opened 2020-07-15 07:42 UTC
If you're scanning someone in a body scanner and they have a soulcrypt, it is identified as an "unknown body" in their upper body.

**Comment by EvilJackCarver** [comment] 2020-07-15 07:44
Closing as duplicate of #267

**Closed by EvilJackCarver** 2020-07-15 07:44 UTC
