### ISSUE TITLE
Kaiser Roach missing dead sprite.

### ISSUE THREAD

**Issue by JackJackery** [Eclipse-Station/NEV-Northern-Light#578] opened 2020-08-24 02:31 UTC
![image](https://user-images.githubusercontent.com/8015239/90997727-a0a7f780-e5c2-11ea-803f-26acba9ed3a2.png)

**Comment by EvilJackCarver** [comment] 2020-08-24 02:47
Closing as duplicate of #289

**Closed by EvilJackCarver** 2020-08-24 02:47 UTC
