### ISSUE TITLE
Species mods like tails and wings draw on the wrong layer when facing north.

### ISSUE THREAD

**Issue by Keekenox** [Eclipse-Station/NEV-Northern-Light#26] opened 2020-05-06 03:16 UTC
https://i.imgur.com/52eIeAd.png Wings are drawing on the wrong layer I think, at least for when you are facing north.

**Comment by EvilJackCarver** [comment] 2020-05-07 00:35
Related to/duplicate of #24.

**Closed** 2020-05-31 23:49 UTC
Labels: Priority: High, Sprites, bug, duplicate
