### ISSUE TITLE
Some objects have invisible held icons, despite working worn icons

### ISSUE THREAD

**Issue by EthanSedgwick** [Eclipse-Station/NEV-Northern-Light#571] opened 2020-08-23 17:28 UTC
Reinforced Medical Shoes are invisible when held, but when worn they can be seen. The icon needs to be added for the held/dropped item.

**Comment by EthanSedgwick** [comment] 2020-08-25 10:49
Engineering hardhat is invisible when held, but when worn works fine.

**Comment by EvilJackCarver** [comment] 2020-08-25 11:34
Please post this in the megathread

---
~ G. A. WILMBROKE

On mobile; typos are my own.

**Comment by EvilJackCarver** [comment] 2020-08-25 13:59
Closing as duplicate of #271

**Closed by EvilJackCarver** 2020-08-25 13:59 UTC
Labels: duplicate
