### ISSUE TITLE
There are no rocks for miners to mine

### ISSUE THREAD

**Issue by Chatter42** [Eclipse-Station/NEV-Northern-Light#120] opened 2020-05-22 01:39 UTC
When the mining shuttle is taken to an asteroid, instead of having anything to do, there's a bunch of empty turfs and they have to turn around and go back home.

**Comment by bearrrrrrrr** [comment] 2020-05-22 01:43
I made an issue of this at #119. Planets themselves are generating fine, but without ores. Unsure if that is unintentional or not.

**Comment by EvilJackCarver** [comment] 2020-05-22 03:40
Closing as duplicate of #119.

**Closed by EvilJackCarver** 2020-05-22 03:40 UTC
Labels: duplicate
