### ISSUE TITLE
Artist uniform borked for non-males

### ISSUE THREAD

**Issue by KoiShenanigans** [Eclipse-Station/NEV-Northern-Light#1428] opened 2021-03-19 22:46 UTC
Title. Artist uniform has a busted or missing sprite for female and plural mobs wearing it.

**Comment by Valanthe500** [comment] 2021-03-23 08:29
Tested and confirmed the issue is from a missing sprite in \icons\inventory\uniform\mob_fem

**Comment by EvilJackCarver** [comment] 2021-04-10 01:10
Closed in #1435

**Closed by EvilJackCarver** 2021-04-10 01:10 UTC
